model:
  - GIN
device:
  - cpu
batch_size:
  - 128
learning_rate:
  - 0.01
classifier_epochs:
  - 150
hidden_units:  # Note: GIN add a first layer that simply adds up all node features
  - [64, 64, 64, 64]
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 50
      gamma: 0.5
loss:
  - MulticlassClassificationLoss
train_eps:
  - false
l2:
  - 0.
aggregation:
  - sum
gradient_clipping:
  - null
dropout:
  - 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 70
      use_loss: False
shuffle:
  - True
resume:
  - False