model:
- SparseCIN
device:
- cpu
aggregation:
- mean
- sum
apply_dropout_before: 
- lin2
batch_size:
- 32
classifier_epochs:
- 150
dropout:
- 0.0
early_stopper:
- args:
    patience: 500
    use_loss: false
  class: Patience
- args:
    patience: 500
    use_loss: true
  class: Patience
final_hidden_multiplier: 
- 2
final_readout: 
- sum
gradient_clipping:
- null
graph_norm: 
- bn
jump_mode: 
- cat
l2:
- 0.0
learning_rate:
- 0.001
loss:
- MulticlassClassificationLoss
max_dim: 
- 2
optimizer:
- Adam
readout_dims:
- (0,1,2)
resume:
- false
scheduler:
- args:
    gamma: 0.5
    step_size: 50
  class: StepLR
shuffle:
- true
train_eps:
- false
use_coboundaries: 
- true
num_layers: 
- 4             
hidden:
- 64          
nonlinearity: 
- relu  
readout: 
- sum 
final_hidden_multiplier: 
- 2        